language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
before_install:
  - sudo apt-get install librsync1 -qq
install:
  - pip install --timeout=30 pep8
  - pip install --timeout=30 pyflakes
  - pip install --timeout=30 -r requirements.txt
  - pip install --timeout=30 -q -e .
before_script:
  - make verify
script:
  - make test
after_success:
  - coveralls
